language: generic
sudo: required

services:
  - dockers
before_install:
  - docker build -t makesaa/multidocker -f Dockerfile.dev .
# script:
#   - docker run -e CI=true makesaa/docker-react npm run test -- --coverage

# deploy:
#   provider: elasticbeanstalk
#   region: "us-east-2"
#   app: "docker-react"
#   env: "DockerReact-env"
#   bucket_name: "elasticbeanstalk-us-east-2-999819961253"
#   bucket_path: "docker-react"
#   on:
#     branch: master
#   access_key_id: $AWS_ACCESS_KEY
#   secret_access_key: $AWS_SECRET_KEY
