# Use  docker image as a base
# here alpine is base image 
FROM nginx

COPY ./default.conf /etc/nginx/conf.d/default.conf

RUN npm install

COPY . .

#tell when to starts as acontainer
CMD ["npm","run", "start"]