# Use  docker image as a base
# here alpine is base image 
FROM node:alpine

#working Directory
WORKDIR /app
# Download and install a Dependency

COPY package.json .
RUN npm install

COPY . .

#tell when to starts as acontainer
CMD ["npm","run", "dev"]